### ISSUE TITLE
关于fusion有什么其他论文和开源推荐吗？

### ISSUE THREAD

**Issue by tangeroo** [ethan-li-coding/Summary-of-3D-Reconstruction#1]
嗨,
  谢谢您的总结。我看到您fusion那块主要是争对SLAM的在线快速融合算法，目前我在做倾斜摄影三维建模的相关研究，我对SLAM和离线三维建模的具体区别不太了解，所以想知道您推荐的这些融合算法是否对离线三维建模也有借鉴意义呢，或者您有没有其他的论文和开源推荐？
  谢谢~

**Comment by ethan-li-coding** [comment]
SLAM和离线实际上同宗同源，SLAM的定位和离线的增量式SFM技术高度重合，SLAM的建图端中的稠密建图即Fusion路线，目前看来和离线重建在具体的算法选型上会有区别，包括点云融合、网格构建的具体算法都不太一样，这和两者的需求、目标及数据情况有关，在线重建帧与帧之间重叠度高，且对效率有较高要求，偏向于用提前设定分辨率的TSDF等融合算法；而离线重建则不会提前设定分辨率，目标是尽可能的重建出细小结构，所以和分辨率无关的融合构网算法更适合。倾斜重建建议看OpenMVS、OpenMVG、Colmap等开源项目。

tangeroo <notifications@github.com> 于2020年9月9日周三 上午11:18写道：

**Comment by tangeroo** [comment]
多谢您的指点，了解了！
